application: visumaps
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /more
  static_dir: more

- url: /data
  static_dir: data

- url: /geocode
  script: geocoder.application

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest